### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by claudiogomezGL** [algolia/instantsearch-ios-insights#23]
**Is your feature request related to a problem? Please describe 🙏**
Since SPM is a first class citizen on Xcode 11, and some of the users of this frameworks are updating to new versions of Xcode, we'd like to start migrating to use SPM instead of other package dependencies. 

**Describe the solution you'd like 🤔**
Add support to SPM for Swift 5 tool chain. 

**Describe alternatives you've considered ✨**

**Additional context**

**Comment by spinach** [comment]
Hello @claudiogomezGL,

Thank you for the feedback, and sorry for the late reply here! We just submitted #24 which adds support for SPM. 

You should now be able to use it in your project. 

Thanks!

**Comment by Lopdo** [comment]
Hello, could you please update readme and add install steps? I know they are trivial, but I was looking at the pods we use now and compiling list of libs that can be moved to SPM and I missed this one since it wasn't mentioned in the readme

**Comment by VladislavFitz** [comment]
Hi @Lopdo ,
The Insights is now a part of the InstantSearch library. You can use its [SPM installation manual](https://github.com/algolia/instantsearch-ios#swift-package-manager). 
Just select the `InstantSearchInsights` from the products list when adding the dependency.
