### ISSUE TITLE
Flush on willResignActive

### ISSUE THREAD

**Issue by abiaad** [algolia/instantsearch-ios-insights#5]
Hello Algolia,

I have one feedback :
It would be nice to try a flush when application is being dismissed (`UIApplication.willResignActiveNotification`)

Cheers,

Pierre

**Comment by VladislavFitz** [comment]
Hello Pierre,
Thank you for your feedback.
It is implemented, you can find this functionality in [beta 5 release](https://github.com/algolia/instantsearch-ios-insights/releases/tag/2.0.0-beta5)
Please let us know if you face any other issues.

**Comment by abiaad** [comment]
Hello @VladislavFitz 
Good on my side. 
Thanks 🙏
